name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    concurrency: release
    environment:
      name: pypi
      url: https://pypi.org/p/cli-mcp

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        enable-cache: true
        cache-dependency-glob: "uv.lock"

    - name: Set up Python
      run: uv python install 3.12

    - name: Install dependencies
      run: |
        uv sync --all-extras --dev

    - name: Check if there is a parent commit
      id: check-parent-commit
      run: |
        echo "has_parent=$(git rev-list --count HEAD)" >> $GITHUB_OUTPUT

    - name: Python Semantic Release Version
      id: version
      if: steps.check-parent-commit.outputs.has_parent != '1'
      run: |
        BEFORE_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
        echo "BEFORE_TAG=$BEFORE_TAG" >> $GITHUB_ENV
        if uv run semantic-release version; then
          AFTER_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
          echo "AFTER_TAG=$AFTER_TAG" >> $GITHUB_ENV
          if [ "$BEFORE_TAG" != "$AFTER_TAG" ]; then
            echo "VERSION_CHANGED=true" >> $GITHUB_ENV
          else
            echo "VERSION_CHANGED=false" >> $GITHUB_ENV
          fi
        else
          echo "VERSION_CHANGED=false" >> $GITHUB_ENV
        fi

    - name: Build package
      if: env.VERSION_CHANGED == 'true'
      run: |
        uv build

    - name: Publish to TestPyPI
      if: env.VERSION_CHANGED == 'true'
      env:
        UV_PUBLISH_TOKEN: ${{ secrets.TEST_PYPI_API_TOKEN }}
      run: |
        uv publish --publish-url https://test.pypi.org/legacy/

    - name: Test install from TestPyPI
      if: env.VERSION_CHANGED == 'true'
      run: |
        uv pip install \
          --index-url https://test.pypi.org/simple/ \
          --extra-index-url https://pypi.org/simple \
          cli-mcp

    - name: Publish to PyPI
      if: env.VERSION_CHANGED == 'true'
      env:
        UV_PUBLISH_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        uv publish

    - name: Publish package distributions to GitHub Releases
      if: env.VERSION_CHANGED == 'true'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        uv run semantic-release publish --verbosity DEBUG
