name: Slack Notifications

on:
  issues:
    types: [opened, closed]
  pull_request:
    types: [opened, closed, merged]
  push:
    branches:
      - main
  release:
    types: [published]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send custom message to Slack
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          text: |
            Event: ${{ github.event_name }}
            Repository: ${{ github.repository }}
            Author: ${{ github.actor }}
            ${{ github.event_name == 'issues' && format('Issue #{0}: {1}', github.event.issue.number, github.event.issue.title) || '' }}
            ${{ github.event_name == 'pull_request' && format('PR #{0}: {1}', github.event.pull_request.number, github.event.pull_request.title) || '' }}
            ${{ github.event_name == 'push' && format('Commit: {0}', github.event.head_commit.message) || '' }}
            ${{ github.event_name == 'release' && format('Release: {0}', github.event.release.tag_name) || '' }}
          webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()
