name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.11", "3.12"]

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        enable-cache: true
        cache-dependency-glob: "uv.lock"

    - name: Set up Python ${{ matrix.python-version }}
      run: uv python install ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        uv sync --all-extras --dev

    - name: Lint with ruff
      run: |
        uv run ruff check src tests --config config/ruff.toml
        uv run ruff format src tests --check --config config/ruff.toml

    - name: Type check
      run: |
        echo "Type checking will be added when mypy is configured"

    - name: Run tests
      run: |
        uv run pytest -xvs -c config/pytest.ini

    - name: Check coverage
      run: |
        uv run coverage run --rcfile=config/.coveragerc -m pytest -c config/pytest.ini
        uv run coverage report --rcfile=config/.coveragerc
        uv run coverage html --rcfile=config/.coveragerc
        # Fail if below minimum coverage
        uv run coverage report --rcfile=config/.coveragerc --fail-under=90
